# This files contains service handlers for Alpine Linux.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
# Usage:
#  handlers:
#    - include: handlers/services.yml

---
# Control handlers for sshd
- name: start sshd
  command: /etc/init.d/sshd start

- name: stop sshd
  command: /etc/init.d/sshd stop

- name: restart sshd
  command: /etc/init.d/sshd restart

# Control handlers for cron
- name: restart cron
  command: /etc/init.d/cron restart
