# This playbook contains operations to perform package management tasks on
# Alpine Linux hosts.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: update the package list
  command: /sbin/apk update
  tags: update_cache
