sshd_port: 22
sshd_host_keys:
  - ecdsa
  - ed25519
sshd_permit_root_login: "yes"
sshd_password_auth: "no"
sshd_settings:
  Protocol: 2
  Ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes256-ctr,aes128-gcm@openssh.com,aes192-ctr"
  MACs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"
  KexAlgorithms: "curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521"
  Compression: "yes"
  ClientAliveInterval: 15
  ClientAliveCountMax: 3
  PermitEmptyPasswords: "no"
  UsePrivilegeSeparation: "yes"
  StrictModes: "yes"
  AuthorizedKeysFile: ".ssh/authorized_keys"
  PubkeyAuthentication: "yes"
  PasswordAuthentication: "no"
  ChallengeResponseAuthentication: "no"
  UseDNS: "no"
  UseLogin: "no"
  PrintLastLog: "yes"
  PrintMotd: "yes"
  Banner: "/etc/issue"
  MaxAuthTries: 6
  IgnoreRhosts: "yes"
  HostbasedAuthentication: "no"
  RhostsRSAAuthentication: "no"
  AllowTcpForwarding: "no"
  X11Forwarding: "no"
  GatewayPorts: "no"
  SyslogFacility: "AUTH"
  LogLevel: "VERBOSE"
  Subsystem: "sftp /usr/lib/ssh/sftp-server"
